# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revelationmodel',
            name='body',
            field=tinymce.models.HTMLField(verbose_name=b'Revelation'),
        ),
        migrations.AlterField(
            model_name='revelationmodel',
            name='datetime',
            field=models.DateTimeField(verbose_name=b'Revelation date'),
        ),
        migrations.AlterField(
            model_name='revelationmodel',
            name='public',
            field=models.BooleanField(default=True, verbose_name=b'Public (directory)'),
        ),
        migrations.AlterField(
            model_name='revelationmodel',
            name='subject',
            field=models.CharField(max_length=100, verbose_name=b'Subject (Public)'),
        ),
    ]
