# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160127_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revelationmodel',
            name='public',
            field=models.BooleanField(default=True, verbose_name=b'Add to public directory'),
        ),
    ]
