# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160223_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revelationmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
