# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160312_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='revelationmodel',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='revelationmodel',
            name='self_destruct',
            field=models.BooleanField(default=False, verbose_name=b'Self destruct on first view'),
        ),
    ]
